### ISSUE TITLE
Is it there a backend that outputs to pure text?

### ISSUE THREAD

**Issue by kito99** [asciidoctor/asciidoctor-backends#121]
I'd like to pull sections out of a JavaScript file into another JavaScript file, so the current back-ends won't do..

**Comment by mojavelinux** [comment]
The closest thing currently is the now deprecated manpage templates (it's deprecated because it's now part of core). They use ERB to output something close to plain text, but it should give you an idea of how it is done.

https://github.com/asciidoctor/asciidoctor-backends/tree/master/erb/manpage

Another way to get plain text (which is what AsciiDoc Python did) was convert the HTML output to plain text using links.

```
$ links -dump output.html
```

**Comment by kito99** [comment]
Where can I find more info on links?

**Comment by mojavelinux** [comment]
Try this page: http://www.sagehill.net/docbookxsl/FormattedText.html

**Comment by kito99** [comment]
Thanks! My course is over, but I'll give it a try the next time I have the
opportunity.

**Comment by mojavelinux** [comment]
:+1:
